[package]
name = "ssh_transport"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
base64 = "0.9.3"
byteorder = "1.2.6"
failure = "0.1.2"
num-bigint = "0.2.0"
