[package]
name = "rssh"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
base64 = "0.10.0"
failure = "0.1.3"
rand = "0.6.1"
sha2 = "0.8.0"
x25519-dalek = "0.3.0"
rust-crypto = "0.2.36"
hex = "0.3.2"
