[package]
name = "ssh_transport"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
base64 = "0.9.3"
byteorder = "1.2.6"
ed25519-dalek = "0.8.1"
failure = "0.1.2"
rand = "0.5.5"
sha2 = "^0.7"
x25519-dalek = "0.3.0"
